name: Enviar Notificaciones

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      branch:
        required: true
        type: string
      actor:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: false
        type: string
      pr_number:
        required: false
        type: string
      commit_message:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true

jobs:
  notify_slack_discord:
    runs-on: ubuntu-latest

    steps:
      - name: 🔔 Enviar Notificaciones
        run: |
          STATUS="${{ inputs.status }}"
          BRANCH="${{ inputs.branch }}"
          ACTOR="${{ inputs.actor }}"
          REPO="${{ inputs.repo }}"
          SHA="${{ inputs.sha }}"
          SHORT_SHA="${SHA:0:7}"
          PR_NUMBER="${{ inputs.pr_number }}"
          COMMIT_MSG="${{ inputs.commit_message }}"

          if [ "$STATUS" = "success" ]; then
            SLACK_COLOR="good"
            TITLE="✅ Despliegue exitoso"
          elif [ "$STATUS" = "failure" ]; then
            SLACK_COLOR="danger"
            TITLE_SLACK="❌ Despliegue fallido"
            TITLE_DISCORD="❌ **Despliegue fallido**"
          elif [ "$STATUS" = "cancelled" ]; then
            SLACK_COLOR="warning"
            TITLE_SLACK="🚫 Despliegue cancelado"
            TITLE_DISCORD="🚫 **Despliegue cancelado**"
          else
            SLACK_COLOR="#CCCCCC"
            TITLE_SLACK="🔍 Estado desconocido: $STATUS"
            TITLE_DISCORD="🔍 **Estado desconocido**: $STATUS"
          fi

          # Mensajes base
          SLACK_MSG="*$TITLE_SLACK* en *$REPO* (\`$BRANCH\`) por \`$ACTOR\` 🚀"
          DISCORD_MSG="$TITLE_DISCORD en **$REPO** (\`$BRANCH\`) por \`$ACTOR\` 🚀"

          # Agregar detalles si existen
          [ -n "$SHORT_SHA" ] && SLACK_MSG="$SLACK_MSG\n• Commit: \`$SHORT_SHA\`"
          [ -n "$SHORT_SHA" ] && DISCORD_MSG="$DISCORD_MSG\n• Commit: \`$SHORT_SHA\`"

          [ -n "$COMMIT_MSG" ] && SLACK_MSG="$SLACK_MSG\n• Mensaje: $COMMIT_MSG"
          [ -n "$COMMIT_MSG" ] && DISCORD_MSG="$DISCORD_MSG\n• Mensaje: $COMMIT_MSG"

          [ -n "$PR_NUMBER" ] && SLACK_MSG="$SLACK_MSG\n• Pull Request: #$PR_NUMBER"
          [ -n "$PR_NUMBER" ] && DISCORD_MSG="$DISCORD_MSG\n• Pull Request: #$PR_NUMBER"

          # Enviar a Slack
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [ {
                \"color\": \"$SLACK_COLOR\",
                \"text\": \"$SLACK_MSG\"
              } ]
            }" ${{ secrets.SLACK_WEBHOOK_URL }}

          # Enviar a Discord
          curl -X POST -H 'Content-Type: application/json' \
            -d "{\"content\": \"$DISCORD_MSG\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}